### PR TITLE
Add support for attachToAllClusters to dbcUpload

### PR DESCRIPTION
**Pull request by brkyvz**
Resolves Issue #19 
@jakajancar Could you please help in testing? Thanks!

This PR will make the uploaded jars automatically attach to all clusters when 
`dbcClusters` contains the value `ALL_CLUSTERS` during `dbcUpload`.

### CODE REVIEW

**Comment by jakajancar** [comment]
@brkyvz It works. Although, I have to say, the design is pretty weird. Whereas previously:

  - `dbcUpload` just uploaded the jars, didn't touch the clusters (although removing old version might unattach the libs)
  - `dbcAttach` attached the existing jars

...now `dbcUpload` also does the attaching — but only for all clusters. If you specify them manually, it doesn't.

That's why I recommended that perhaps dbcUpload should remain as-is, but special handling of ALL_CLUSTERS in dbcAttach would be changed from going over all the clusters, to just sending __ALL_CLUSTERS to the API.

Anyway, just my 2c, this works and fixes the problem for me :)

**Comment by brkyvz** [comment]
@jakajancar I'm happy the method works! 
The second case (your suggestion) makes more sense design wise (dbcAttach). I'll make that change, since that's also going to be simple as well.

**Comment by brkyvz** [comment]
@jakajancar Made the changes you proposed. I tested it, and it seems fine. Could you please verify the `dbcAttach` approach? Thanks!

**Comment by jakajancar** [comment]
Works! Can you make a release?

**Comment by brkyvz** [comment]
I can. I'll get that other "issue" out of the way as well, and make one

**Comment by jakajancar** [comment]
@brkyvz Any update on the release? Sorry to be pushy...

**Comment by brkyvz** [comment]
@jakajancar I'll get the release published tomorrow. Naming libraries will have to wait though if that's okay.

**Comment by ahirreddy** [comment]
LGTM

**Comment by brkyvz** [comment]
Thanks @ahirreddy Merging.

**Comment by jakajancar** [comment]
Thanks again for this @brkyvz !

**Pull request merged**
